---
title: "Oscilações Harmônicas Simples: Sistema Massa-Mola"
lang: pt-BR
format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
  pdf:
    documentclass: article
    template: ../../_templates/latex/template.tex
    toc: false
    number-sections: true
---

# Introdução

Considere uma massa $m$ conectada a uma mola ideal cuja constante elástica é igual a $k$, conforme mostra a Figura \ref{fig_1}. Este sistema é geralmente denominado \textbf{sistema massa-mola}. Inicialmente, a mola está em repouso e em posição de equilíbrio. O sistema está imersa em um meio, por exemplo o ar, cuja resistência ao movimento pode ser desprezada.

# Objetivos

- Compreender o funcionamento do paquímetro;
- Aprender a realizar medições precisas;
- Analisar as fontes de erro na medição.

# Materiais

- Paquímetro;
- Objetos para medição (ex: blocos, tubos);

# Procedimentos

1. Verificar a calibração do paquímetro.
2. Medir a dimensão externa dos objetos.
3. Medir a dimensão interna dos objetos.
4. Medir a profundidade dos objetos.
5. Anotar os resultados e calcular as incertezas.

# Referências



